#!/usr/bin/env python3
"""Generate the shared website palette CSS from the canonical JSON source."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PALETTE_PATH = ROOT / "config/visual_palette.json"
CSS_PATH = ROOT / "docs/assets/palette.css"
HEX_COLOR = re.compile(r"#[0-9A-F]{6}")


def render_palette() -> str:
    palette = json.loads(PALETTE_PATH.read_text(encoding="utf-8"))
    if palette.pop("schema-version", None) != 1:
        raise ValueError("visual palette must use schema-version 1")
    invalid = {key: value for key, value in palette.items() if not isinstance(value, str) or not HEX_COLOR.fullmatch(value)}
    if invalid:
        raise ValueError(f"invalid palette entries: {invalid}")
    variables = "\n".join(f"  --{key}: {value.lower()};" for key, value in palette.items())
    return (
        "/* Generated by tools/build_visual_palette.py; edit config/visual_palette.json. */\n"
        ":root {\n"
        f"{variables}\n"
        "}\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if palette.css is stale")
    args = parser.parse_args()
    expected = render_palette()
    if args.check:
        actual = CSS_PATH.read_text(encoding="utf-8") if CSS_PATH.is_file() else ""
        if actual != expected:
            raise SystemExit("docs/assets/palette.css is stale; run tools/build_visual_palette.py")
        return
    CSS_PATH.write_text(expected, encoding="utf-8")


if __name__ == "__main__":
    main()
